[package]
name = "kurosawa_akira"
version = "0.1.0"

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true
allowed-libfuncs-list.name = "all"

[dependencies]
starknet = ">=2.4.4"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.14.0" }

[[tool.snforge.fork]]
name = "block_based"
url = "https://starknet-testnet.public.blastapi.io/rpc/v0_6"
block_id.number = "915484"
