[package]
name = "kurosawa_akira"
version = "0.1.0"

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true
allowed-libfuncs-list.name = "all"

[dependencies]
starknet = "2.6.3"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.23.0" }


[[tool.snforge.fork]]
name = "block_based"
url = "https://rpc.nethermind.io/sepolia-juno?apikey=l6MkRPgfPwdrAS5o7hbnWGUJG52Ol540i24oa6QxyzRnhTBa"
block_id.number = "67186"
